arbeidsrett:
  domain_name: "arbeidsrett"
  xapi_rettsomrader:
    - "Arbeidsrett"
  q: []

arsregnskap_og_selskapsrapportering:
  domain_name: "arsregnskap_og_selskapsrapportering"
  xapi_rettsomrader:
    - "Regnskap"
    - "Bank, finans og regnskapsrett"
  q: []

avtalerett:
  domain_name: "avtalerett"
  xapi_rettsomrader:
    - "Avtaler"
    - "Anskaffelser, avtaler, bygg og entrepriser"
    - "Forbruker-, kjøps- og konkurranserett"
    - "Kjøp"
    - "Forbrukerkjøp"
  q:
    - "avtaleloven"
    - "kontrakt"

inkasso_og_tvangsfullbyrdelse:
  domain_name: "inkasso_og_tvangsfullbyrdelse"
  xapi_rettsomrader:
    - "Tvangsfullbyrdelse"
  q:
    - "inkasso"

konkursrett_og_insolvens:
  domain_name: "konkursrett_og_insolvens"
  xapi_rettsomrader:
    - "Konkurs, gjeld og pant"
    - "Gjeldsforhandling. Konkurs"
  q:
    - "konkurs"
    - "insolvens"

manda_fusjon_fisjon:
  domain_name: "manda_fusjon_fisjon"
  xapi_rettsomrader: []
  q:
    - "fusjon"
    - "fisjon"

obligasjonsrett:
  domain_name: "obligasjonsrett"
  xapi_rettsomrader: []
  q:
    - "obligasjon"
    - "mislighold"
    - "erstatning"

panterett_og_sikkerhetsrett:
  domain_name: "panterett_og_sikkerhetsrett"
  xapi_rettsomrader:
    - "Pant"
    - "Konkurs, gjeld og pant"
  q:
    - "sikkerhetsrett"

pengekravsrett_fordringer:
  domain_name: "pengekravsrett_fordringer"
  xapi_rettsomrader: []
  q:
    - "pengekrav"
    - "fordring"
    - "gjeld"

personvern_gdpr_business_compliance:
  domain_name: "personvern_gdpr_business_compliance"
  xapi_rettsomrader:
    - "Personrett. Personvern"
    - "Personopplysninger"
  q:
    - "personvern"
    - "GDPR"

selskapsrett:
  domain_name: "selskapsrett"
  xapi_rettsomrader:
    - "Selskaper, fond og foreninger"
    - "Aksjeselskaper og allmennaksjeselskaper"
  q: []

tvistelosning_smb:
  domain_name: "tvistelosning_smb"
  xapi_rettsomrader:
    - "Sivilprosess/tvisteloven"
    - "Domstolloven"
  q:
    - "tvist"
    - "forliksråd"
    - "voldgift"